<?php
echo '<!DOCTYPE html>';
echo '<html dir="ltr" lang="en-US">';
echo '<head>';
echo '';
echo '<meta http-equiv="content-type" content="text/html; charset=utf-8" />';
echo '<meta name="author" content="The Professional Recruiter" />';
echo '';
echo '<!-- Stylesheets';
echo '============================================= -->';
echo '<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">';
echo '<link rel="stylesheet" href="css/bootstrap.css" type="text/css" />';
echo '<link rel="stylesheet" href="style.css" type="text/css" />';
echo '<link rel="stylesheet" href="css/swiper.css" type="text/css" />';
echo '<link rel="stylesheet" href="css/dark.css" type="text/css" />';
echo '<link rel="stylesheet" href="css/font-icons.css" type="text/css" />';
echo '<link rel="stylesheet" href="css/animate.css" type="text/css" />';
echo '<link rel="stylesheet" href="css/magnific-popup.css" type="text/css" />';
echo '<link rel="icon" href="favicon.png" type="image/png" sizes="16x16">';
echo '<link rel="stylesheet" href="css/responsive.css" type="text/css" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<!--[if lt IE 9]>';
echo '<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>';
echo '<![endif]-->';
echo '';
echo '<!-- Document Title';
echo '============================================= -->';
echo '<title>Home - The Professional Recruiter</title>';
echo '<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>';
echo '';
echo '<script type="text/javascript">';
echo '// When the window has finished loading create our google map below';
echo 'google.maps.event.addDomListener(window, 'load', init);';
echo '';
echo 'function init() {';
echo '';
echo '';
echo '// Basic options for a simple Google Map';
echo '// For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions';
echo 'var mapOptions = {';
echo '// How zoomed in you want the map to start at (always required)';
echo 'zoom: 17,';
echo '';
echo '// The latitude and longitude to center the map (always required)';
echo 'center: new google.maps.LatLng(-31.887260, 115.999700), // New York';
echo '';
echo '// How you would like to style the map.';
echo '// This is where you would paste any style found on Snazzy Maps.';
echo 'styles: [{"stylers":[{"saturation":-100},{"gamma":0.8},{"lightness":4},{"visibility":"on"}]},{"featureType":"landscape.natural","stylers":[{"visibility":"on"},{"color":"#ffffff"},{"gamma":6.97},{"lightness":-5},{"saturation":100}]}]';
echo '};';
echo '';
echo '// Get the HTML DOM element that will contain your map';
echo '// We are using a div with id="map" seen below in the <body>';
echo 'var mapElement = document.getElementById('map');';
echo '';
echo '// Create the Google Map using our element and options defined above';
echo 'var map = new google.maps.Map(mapElement, mapOptions);';
echo '';
echo '// Let's also add a marker while we're at it';
echo 'var image = 'images/marker.png';';
echo 'var beachMarker = new google.maps.Marker({';
echo 'position: {lat: -31.887260, lng: 115.999700},';
echo 'map: map,';
echo 'icon: image,';
echo 'title: 'The Professional Recruiter'';
echo '});';
echo '}';
echo '</script>';
echo '</head>';
echo '';
echo '<body class="stretched">';
echo '';
echo '<!-- Document Wrapper';
echo '============================================= -->';
echo '<div id="wrapper" class="clearfix">';
echo '';
echo '<!-- Header';
echo '============================================= -->';
echo '<header id="header" class="full-header">';
echo '';
echo '<div id="header-wrap">';
echo '';
echo '<div class="container clearfix">';
echo '';
echo '<div id="primary-menu-trigger"><i class="icon-reorder"></i></div>';
echo '';
echo '<!-- Logo';
echo '============================================= -->';
echo '<div id="logo">';
echo '<a href="index.html" class="standard-logo" data-dark-logo="images/logo-dark.png"><img src="images/logo.png" alt="Canvas Logo"></a>';
echo '<a href="index.html" class="retina-logo" data-dark-logo="images/logo-dark@2x.png"><img src="images/logo@2x.png" alt="Canvas Logo"></a>';
echo '</div><!-- #logo end -->';
echo '';
echo '<!-- Primary Navigation';
echo '============================================= -->';
echo '<nav id="primary-menu">';
echo '';
echo '<ul>';
echo '<li class="current"><a href="index.html"><div>Home</div></a></li>';
echo '<li><a href="about_us.html"><div>About Us</div></a></li>';
echo '<li><a href="our_service.html"><div>Our Service</div></a></li>';
echo '<li><a href="contact.html"><div>Contact Us</div></a></li>';
echo '</ul>';
echo '';
echo '<!-- Top Search';
echo '============================================= -->';
echo '<div class="menubar"></div>';
echo '';
echo '</nav><!-- #primary-menu end -->';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</header><!-- #header end -->';
echo '';
echo '';
echo '<div class="swiperBub"></div>';
echo '<section id="slider" class="slider-parallax swiper_wrapper clearfix" data-loop="true" data-autoplay="3000">';
echo '<div class="menuBorder"></div>';
echo '<div class="slider-parallax-inner">';
echo '<div class="swiper-container swiper-parent">';
echo '<div class="swiperMask"><img src="images/slider/swiper/mask.png"></div>';
echo '';
echo '<div class="swiperBub2"></div>';
echo '<div class="swiperBub3"></div>';
echo '<div class="swiper-wrapper">';
echo '';
echo '<div class="swiper-slide dark" style="background-image: url('images/slider/swiper/1.jpg');" onClick="location.href='about_us.html';">';
echo '<div class="container clearfix">';
echo '<div class="slider-caption slider-caption-center">';
echo '<div class="welcomeBox" data-caption-animate="fadeInDown" data-caption-delay="0">Welcome to The Professional Recruiter</div>';
echo '<h2 data-caption-animate="fadeInUp" data-caption-delay="0">Your Difficulties<br/>We Solve</h2>';
echo '<div class="cta" data-caption-animate="fadeInUp" data-caption-delay="400"><a href="about_us.html" target="_parent">Explore more</a></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="swiper-slide dark" style="background-image: url('images/slider/swiper/2.jpg');" onClick="location.href='about_us.html';">';
echo '<div class="container clearfix">';
echo '<div class="slider-caption slider-caption-center">';
echo '<div class="welcomeBox" data-caption-animate="fadeInDown" data-caption-delay="0">Welcome to The Professional Recruiter</div>';
echo '<h2 data-caption-animate="fadeInUp" data-caption-delay="0">Your Prospects<br/>We Care</h2>';
echo '<div class="cta" data-caption-animate="fadeInUp" data-caption-delay="400"><a href="about_us.html" target="_parent">Explore more</a></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="swiper-slide dark" style="background-image: url('images/slider/swiper/3.jpg');" onClick="location.href='about_us.html';">';
echo '<div class="container clearfix">';
echo '<div class="slider-caption slider-caption-center">';
echo '<div class="welcomeBox" data-caption-animate="fadeInDown" data-caption-delay="0">Welcome to The Professional Recruiter</div>';
echo '<h2 data-caption-animate="fadeInUp" data-caption-delay="0">The right person, the right place, <br/>at the right time</h2>';
echo '<div class="cta" data-caption-animate="fadeInUp" data-caption-delay="400"><a href="about_us.html" target="_parent">Explore more</a></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="slider-arrow-left"><i class="icon-angle-left"></i></div>';
echo '<div id="slider-arrow-right"><i class="icon-angle-right"></i></div>';
echo '<!--div id="slide-number"><div id="slide-number-current"></div><span>/</span><div id="slide-number-total"></div></div-->';
echo '<div class="swiper-pagination"></div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section id="content">';
echo '<div class="content-wrap" style="padding-bottom:0;">';
echo '<div class="container clearfix" style="padding-bottom:80px;">';
echo '<h4 class="heading">Our Expertises</h4>';
echo '<div class="col_one_third nobottommargin">';
echo '<div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">';
echo '<div class="fbox-icon">';
echo '<img src="images/icon01.png" style="height:92px; width:92px;">';
echo '</div>';
echo '<h3>Permanent Job Placement</h3>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col_one_third nobottommargin">';
echo '<div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">';
echo '<div class="fbox-icon">';
echo '<img src="images/icon02.png" style="height:92px; width:92px;">';
echo '</div>';
echo '<h3 class="superWide">Mass Recruitment Project / Secondment Services</h3>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="col_one_third nobottommargin col_last">';
echo '<div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">';
echo '<div class="fbox-icon">';
echo '<img src="images/icon03.png" style="height:92px; width:92px;">';
echo '</div>';
echo '<h3>Temporary / Contract Staffing</h3>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="section parallax nomargin notopborder dark" style="background-image: url('images/parallax/2.jpg'); padding: 100px 0;" data-stellar-background-ratio="0.3">';
echo '<div class="container clearfix">';
echo '<h4 class="heading">Why The Professional Recruiter</h4>';
echo '<div class="centerLine"></div>';
echo '<div class="backetLine"></div>';
echo '<div class="row">';
echo '<div class="col-md-4 bottommargin">';
echo '<div class="testimonial">';
echo '<div class="testi-content">';
echo '<span>Extensive Talent Pool</span>';
echo '<p>We are constantly building personal networks with various candidates in Australia, and able to approach special and silent job';
echo 'seekers. And we keep extending sourcing channels by holding seminars and recruitment talk in education institutes and exhibitions.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-4 bottommargin">';
echo '<div class="testimonial">';
echo '<div class="testi-content">';
echo '<span>Proven Track Record</span>';
echo '<p>We have a proven track record in';
echo 'delivering best-fit talents for some of the multinational companies across various industries. It is a clear indicator which we are confident of successfully matching job-seekers to vacancies.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-4 bottommargin">';
echo '<div class="testimonial">';
echo '<div class="testi-content">';
echo '<span>Reliable Services</span>';
echo '<p>Our business consultants are trained to work very closely with clients, from requirement gathering, candidate seraching, interview management to after care services. The major purpose is to ensure that the result can meet the clients’ ultimate objectives.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '<div class="backetLineBottom"></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="clearfix" style="padding:80px 0 0 0; width:100%; margin:0;">';
echo '<h4 class="heading">Contact Us</h4>';
echo '<div id="map" class="googleMap"></div>';
echo '<div class="col_full nobottommargin common-height">';
echo '';
echo '<div class="col-md-3 dark col-padding ohidden center" style="background-color: #06101a; color:#FFFFFF">';
echo '<div>';
echo '<h3 class="uppercase" style="font-weight: 700; color:#FFFFFF;">Telephone</h3>';
echo '<p style="line-height: 1.1;">(08) 9034 8654</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-3 dark col-padding ohidden center" style="background-color: #161d25; color:#FFFFFF">';
echo '<div>';
echo '<h3 class="uppercase" style="font-weight: 700; color:#FFFFFF;">Fax</h3>';
echo '<p style="line-height: 1.1;">(08) 9034 8654</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-3 dark col-padding ohidden center" style="background-color: #14181c; color:#FFFFFF">';
echo '<div>';
echo '<h3 class="uppercase" style="font-weight: 700; color:#FFFFFF;">Email</h3>';
echo '<p style="line-height: 1.1;"><a href="mailto:info@theprofessionalrecruiter.com" style="color:#FFFFFF; text-decoration:underline;">info@theprofessionalrecruiter.com</a></p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-3 dark col-padding ohidden center" style="background-color: #06101a; color:#FFFFFF">';
echo '<div>';
echo '<h3 class="uppercase" style="font-weight: 700; color:#FFFFFF;">Address</h3>';
echo '<p style="line-height: 1.5;">25 William Street, Perth, WA, 6000. Australia</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="clear"></div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '<footer>';
echo '<div class="toTop">';
echo '<div class="color"><img src="images/footerColor.gif"></div>';
echo '<div class="topButton" id="gotoTop">TOP</div>';
echo '</div>';
echo '<div class="footerMenu">';
echo '<div class="menuRight">';
echo '<a href="index.html">Home</a>';
echo '<a href="about_us.html">About Us</a>';
echo '<a href="our_service.html">Our Service</a>';
echo '<a href="contact.html">Contact Us</a>';
echo '<span>Copyright @ The Professional Recruiter. All rights reserved.</span>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';
echo '</div><!-- #wrapper end -->';
echo '';
echo '<!-- Go To Top';
echo '============================================= -->';
echo '';
echo '<!-- External JavaScripts';
echo '============================================= -->';
echo '<script type="text/javascript" src="js/jquery.js"></script>';
echo '<script type="text/javascript" src="js/plugins.js"></script>';
echo '';
echo '<!-- Footer Scripts';
echo '============================================= -->';
echo '<script type="text/javascript" src="js/functions.js"></script>';
echo '<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvE9FSI0fEf6900ndOufDIQN1LCY4Dq10&callback=initMap" async defer></script>';
echo '';
echo '</body>';
echo '</html>';
?>
